import { Offer, Business, Category } from '../types/database';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Tous', icon: 'apps-outline', sort_order: 0, created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Boulangeries', icon: 'nutrition-outline', sort_order: 1, created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Pâtisseries', icon: 'cafe-outline', sort_order: 2, created_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Fast-food', icon: 'fast-food-outline', sort_order: 3, created_at: new Date().toISOString() },
  { id: 'cat-5', name: 'Restaurants', icon: 'restaurant-outline', sort_order: 4, created_at: new Date().toISOString() },
  { id: 'cat-6', name: 'Cafés', icon: 'beer-outline', sort_order: 5, created_at: new Date().toISOString() },
  { id: 'cat-7', name: 'Supermarchés', icon: 'cart-outline', sort_order: 6, created_at: new Date().toISOString() },
  { id: 'cat-8', name: 'Épiceries', icon: 'basket-outline', sort_order: 7, created_at: new Date().toISOString() },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'biz-1',
    owner_id: 'user-biz-1',
    name: "Boulangerie L'Artisan d'Alger",
    description: "Boulangerie artisanale au cœur d'Alger Centre. Pains spéciaux, baguettes traditionnelles et viennoiseries croustillantes cuites deux fois par jour.",
    phone: "0550 12 34 56",
    address: "14 Rue Didouche Mourad, Alger Centre",
    wilaya: "Alger",
    latitude: 36.7725,
    longitude: 3.0586,
    status: 'active',
    opening_hours: "07:00 - 21:00",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'biz-2',
    owner_id: 'user-biz-2',
    name: "Pâtisserie La Rose de Bab Ezzouar",
    description: "Créateur de douceurs sucrées. Pâtisserie fine, gâteaux traditionnels algériens, mille-feuilles et tartes de saison.",
    phone: "0661 98 76 54",
    address: "Cité 5 Juillet, Bab Ezzouar",
    wilaya: "Alger",
    latitude: 36.7196,
    longitude: 3.1833,
    status: 'active',
    opening_hours: "08:00 - 22:00",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'biz-3',
    owner_id: 'user-biz-3',
    name: "Burger & Co Sidi Yahia",
    description: "Fast-food gourmet réputé pour ses steaks hachés frais, frites maison et burgers généreux à emporter.",
    phone: "0770 33 44 55",
    address: "Boulevard Sidi Yahia, Hydra",
    wilaya: "Alger",
    latitude: 36.7389,
    longitude: 3.0334,
    status: 'active',
    opening_hours: "11:30 - 23:30",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'off-1',
    business_id: 'biz-1',
    name: 'Panier Pains & Viennoiseries',
    description: "Assortiment surprise composé de 2 baguettes tradition, 3 croissants au beurre et 2 pains au chocolat cuits ce matin.",
    price: 250,
    estimated_value: 800,
    initial_quantity: 5,
    available_quantity: 3,
    start_at: new Date(Date.now() - 3600000).toISOString(),
    end_at: new Date(Date.now() + 7200000).toISOString(),
    status: 'available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    business: MOCK_BUSINESSES[0],
  },
  {
    id: 'off-2',
    business_id: 'biz-2',
    name: 'Panier Pâtisseries & Douceurs',
    description: "4 parts de gâteaux variés du jour (mille-feuille croustillant, éclairs au café et tartelette aux fruits).",
    price: 350,
    estimated_value: 1200,
    initial_quantity: 3,
    available_quantity: 2,
    start_at: new Date(Date.now() - 1800000).toISOString(),
    end_at: new Date(Date.now() + 10800000).toISOString(),
    status: 'available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    business: MOCK_BUSINESSES[1],
  },
  {
    id: 'off-3',
    business_id: 'biz-3',
    name: 'Panier Fast-Food du Soir',
    description: "1 burger gourmet complet + portion généreuse de frites et boisson fraîche du service de midi.",
    price: 400,
    estimated_value: 1100,
    initial_quantity: 4,
    available_quantity: 1,
    start_at: new Date(Date.now() + 3600000).toISOString(),
    end_at: new Date(Date.now() + 14400000).toISOString(),
    status: 'available',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    business: MOCK_BUSINESSES[2],
  },
  {
    id: 'off-4',
    business_id: 'biz-1',
    name: 'Panier Baguettes Spéciales',
    description: "Lot de 4 baguettes aux céréales et pain de campagne artisanal.",
    price: 150,
    estimated_value: 500,
    initial_quantity: 2,
    available_quantity: 0,
    start_at: new Date(Date.now() - 7200000).toISOString(),
    end_at: new Date(Date.now() + 3600000).toISOString(),
    status: 'sold_out',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    business: MOCK_BUSINESSES[0],
  }
];
